version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: make
          name: build
      - run:
          command: make push-image
          name: push image

workflows:
  weekly:
    triggers:
      - schedule:
          cron: "20 20 * * 2"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
